name: media_filters
description: "Apply filters on visual media using hardware acceleration"
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  jni: ^0.14.2
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  jnigen: ^0.14.2

flutter:
  plugin:
    platforms:
      android:
        package: dev.arish.media_filters
        pluginClass: MediaFiltersPlugin
      ios:
        pluginClass: MediaFiltersPlugin
